# G920 state
WHEEL_CONTROLLER_STEERING_MIN: int = -32767
WHEEL_CONTROLLER_ACCELERATOR_MID: int = 32767
WHEEL_CONTROLLER_ACCELERATOR_MAX: int = 65535
# button index for Logitech G920 steering wheel controller
BUTTON_A_INDEX: int = 0
BUTTON_B_INDEX: int = 1
BUTTON_X_INDEX: int = 2
BUTTON_Y_INDEX: int = 3
BUTTON_UP_INDEX: int = 4
BUTTON_DOWN_INDEX: int = 5
BUTTON_MENU_INDEX: int = 6
BUTTON_VIEW_INDEX: int = 7
BUTTON_RSB_INDEX: int = 8
BUTTON_LSB_INDEX: int = 9
BUTTON_XBOX_INDEX: int = 10
